require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


#require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
#require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
#require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")


platform :ios, '16.0'

#pod 'Mapbox-iOS-SDK', '~> 6.0'
#pod 'MapboxMobileEvents', '~> 1.0'

#require 'json'
#podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

install! 'cocoapods', :disable_input_output_paths => true
use_frameworks!
#use_frameworks! :linkage => :static

$RNFirebaseAsStaticFramework = true

target 'turvyDriver' do
  pod 'ASN1Decoder'
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  #use_react_native!(
  #  :path => config[:reactNativePath],
  #  :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
  #)

  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  #   post_install do |installer|
  #     flipper_post_install(installer)
  #   end
  # end

  #pre_install do |installer|
  #  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  #end

  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNSVG')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end

#  post_install do |installer|
#    react_native_post_install(installer)

    # Workaround `Cycle inside FBReactNativeSpec` error for react-native 0.64
    # Reference: https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933
#    installer.pods_project.targets.each do |target|
#      if (target.name&.eql?('FBReactNativeSpec'))
#        target.build_phases.each do |build_phase|
#         if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
#            target.build_phases.move(build_phase, 0)
#          end
#        end
#      end
#    end
#  end


end
